export const TOTAL_USERS_REQUEST = "TOTAL_USERS_REQUEST";
export const TOTAL_USERS_SUCCESS = "TOTAL_USERS_SUCCESS";
export const TOTAL_USERS_FAIL = "TOTAL_USERS_FAIL";

export const TOTAL_WALLET_VALUE_REQUEST = "TOTAL_WALLET_VALUE_REQUEST";
export const TOTAL_WALLET_VALUE_SUCCESS = "TOTAL_WALLET_VALUE_SUCCESS";
export const TOTAL_WALLET_VALUE_FAIL = "TOTAL_WALLET_VALUE_FAIL";

export const TOTAL_TRANSFER_REQUEST = "TOTAL_TRANSFER_REQUEST";
export const TOTAL_TRANSFER_SUCCESS = "TOTAL_TRANSFER_SUCCESS";
export const TOTAL_TRANSFER_FAIL = "TOTAL_TRANSFER_FAIL";

export const TOTAL_WITHDRAWS_REQUEST = "TOTAL_WITHDRAWS_REQUEST";
export const TOTAL_WITHDRAWS_SUCCESS = "TOTAL_WITHDRAWS_SUCCESS";
export const TOTAL_WITHDRAWS_FAIL = "TOTAL_WITHDRAWS_FAIL";