export const DEPOSIT_CREATE_REQUEST = "DEPOSIT_CREATE_REQUEST";
export const DEPOSIT_CREATE_SUCCESS = "DEPOSIT_CREATE_SUCCESS";
export const DEPOSIT_CREATE_FAIL = "DEPOSIT_CREATE_FAIL";
export const DEPOSIT_CREATE_RESET = "DEPOSIT_CREATE_RESET";
