export const TRANSACTION_DETAILS_REQUEST = "TRANSACTION_DETAILS_REQUEST";
export const TRANSACTION_DETAILS_SUCCESS = "TRANSACTION_DETAILS_SUCCESS";
export const TRANSACTION_DETAILS_FAIL = "TRANSACTION_DETAILS_FAIL";
