export const TRANSFER_CREATE_REQUEST = "TRANSFER_CREATE_REQUEST";
export const TRANSFER_CREATE_SUCCESS = "TRANSFER_CREATE_SUCCESS";
export const TRANSFER_CREATE_FAIL = "TRANSFER_CREATE_FAIL";
export const TRANSFER_CREATE_RESET = "TRANSFER_CREATE_RESET";
