export const WITHDRAW_CREATE_REQUEST = "WITHDRAW_CREATE_REQUEST";
export const WITHDRAW_CREATE_SUCCESS = "WITHDRAW_CREATE_SUCCESS";
export const WITHDRAW_CREATE_FAIL = "WITHDRAW_CREATE_FAIL";
export const WITHDRAW_CREATE_RESET = "WITHDRAW_CREATE_RESET";
